import streamlit as st
import json
import pandas as pd

# ==========================================
# ロジック部分 (JSON生成関数)
# ==========================================
def generate_pedigree_data(paternal_sibs, maternal_sibs, father_idx, mother_idx, my_sibs, self_idx):
    """
    入力データからHeredicTree用JSON辞書を生成する
    """
    # 全叔父叔母・親世代のリスト（父方 + 母方）
    gen2_genders = paternal_sibs + maternal_sibs
    
    # インデックス調整 (1-based -> 0-based)
    f_idx = father_idx - 1
    m_idx = mother_idx - 1
    s_idx = self_idx - 1

    individuals = []
    relationships = []

    # --- 1. 第一世代 (祖父母) ---
    # 父方
    individuals.append({"id": "I-1", "gender": "M", "label": "Paternal GF"})
    individuals.append({"id": "I-2", "gender": "F", "label": "Paternal GM"})
    # 母方
    individuals.append({"id": "I-3", "gender": "M", "label": "Maternal GF"})
    individuals.append({"id": "I-4", "gender": "F", "label": "Maternal GM"})

    # --- 2. 第二世代 (親・叔父叔母) ---
    gen2_ids = []
    paternal_children_ids = []
    maternal_children_ids = []

    for i, gender in enumerate(gen2_genders):
        indi_id = f"II-{i+1}"
        gen2_ids.append(indi_id)
        
        label = ""
        # ユーザー指定のインデックスと一致する場合にラベル付与
        if i == f_idx:
            label = "Father"
        elif i == m_idx:
            label = "Mother"

        individuals.append({
            "id": indi_id,
            "gender": gender,
            "label": label,
            "affected": "",
            "deceased": "",
            "proband": "",
            "client": "",
            "documented": "",
            "pregnancy": ""
        })

        # 父方リストの長さ内なら父方祖父母の子
        if i < len(paternal_sibs):
            paternal_children_ids.append(indi_id)
        else:
            maternal_children_ids.append(indi_id)

    # 祖父母 -> 第二世代の関係
    if paternal_children_ids:
        relationships.append({
            "p1": "I-1", "p2": "I-2",
            "children": paternal_children_ids,
            "divorced": "", "multiples": [], "adopted_in": [], "adopted_out": [], "consanguinity": ""
        })
    if maternal_children_ids:
        relationships.append({
            "p1": "I-3", "p2": "I-4",
            "children": maternal_children_ids,
            "divorced": "", "multiples": [], "adopted_in": [], "adopted_out": [], "consanguinity": ""
        })

    # --- 3. 第三世代 (自分・兄弟姉妹) ---
    gen3_ids = []
    
    # 親IDの特定 (インデックスが範囲外でないかチェック)
    father_id = gen2_ids[f_idx] if 0 <= f_idx < len(gen2_ids) else None
    mother_id = gen2_ids[m_idx] if 0 <= m_idx < len(gen2_ids) else None

    for i, gender in enumerate(my_sibs):
        indi_id = f"III-{i+1}"
        gen3_ids.append(indi_id)

        is_self = (i == s_idx)
        label = "Self" if is_self else ""
        
        individuals.append({
            "id": indi_id,
            "gender": gender,
            "label": label,
            "proband": is_self,
            "client": is_self,
            "affected": "",
            "deceased": "",
            "documented": "",
            "pregnancy": ""
        })

    # 両親 -> 第三世代の関係
    if father_id and mother_id:
        relationships.append({
            "p1": father_id,
            "p2": mother_id,
            "children": gen3_ids,
            "divorced": "", "multiples": [], "adopted_in": [], "adopted_out": [], "consanguinity": ""
        })

    # --- JSON構築 ---
    output_json = {
        "meta": {"comments": "Generated by Streamlit App"},
        "layout": {
            "partner_spacing": 1.5,
            "min_sib_spacing": 2.0,
            "gen_height": 4.0,
            "family_gap": 1.0,
            "u_shape_offset": 2.0,
            "adjustment_iterations": 1,
            "layout_priority": "Children to Parents (Top-down)",
            "symbol_size": 1.0,
            "line_width": 1.5,
            "font_size": 10,
            "label_offset": 0.2,
            "node_width": 1
        },
        "individual": individuals,
        "relationships": relationships
    }
    return output_json

def parse_input_string(s):
    """カンマ区切りの文字列をリストに変換 (例: 'M, F' -> ['M', 'F'])"""
    s = s.replace("、", ",") # 全角カンマ対応
    return [x.strip() for x in s.split(",") if x.strip()]

# ==========================================
# UI部分 (Streamlit)
# ==========================================
st.set_page_config(page_title="JSON Generator", layout="wide")

st.title("Easy Pedigree Generator")
st.markdown("HeredicTree用のJSONファイルを生成します。")

# --- セクション1 ---
col1, col2, col3 = st.columns(3)
with col1:
    p_str = st.text_input("父方の兄弟姉妹 (例: M, F, M)", value="M", help="例: M, F, M")
with col2:
    m_str = st.text_input("母方の兄弟姉妹 (例: F, M)", value="F", help="例: F, M")
with col3:
    s_str = st.text_input("発端者世代の構成 (例: F, M)", value="", help="例: F, M")

# リスト変換
p_sibs = parse_input_string(p_str)
m_sibs = parse_input_string(m_str)
all_gen2 = p_sibs + m_sibs
my_sibs = parse_input_string(s_str)

# 両親の選択
col4, col5, col6 = st.columns(3)
with col4:
    father_local_idx = st.number_input("父親は「父方の兄弟姉妹」の何番目？", 
                                       min_value=1, 
                                       max_value=len(p_sibs) if p_sibs else 1, 
                                       value=1)
    father_idx = father_local_idx

with col5:
    mother_local_idx = st.number_input("母親は「母方の兄弟姉妹」の何番目？", 
                                       min_value=1, 
                                       max_value=len(m_sibs) if m_sibs else 1, 
                                       value=1)
    mother_idx = len(p_sibs) + mother_local_idx
with col6:
    self_idx = st.number_input("発端者は「発端者世代」の何番目？", 
                               min_value=1, 
                               max_value=len(my_sibs) if my_sibs else 1)

st.markdown("---")

# --- 生成ボタン ---
if st.button("JSONファイルを生成", type="primary"):
    if not all_gen2 or not my_sibs:
        st.error("入力項目を確認してください")
    else:
        # JSON生成
        result_json = generate_pedigree_data(
            paternal_sibs=p_sibs,
            maternal_sibs=m_sibs,
            father_idx=father_idx,
            mother_idx=mother_idx,
            my_sibs=my_sibs,
            self_idx=self_idx
        )
        
        # JSON文字列化
        json_str = json.dumps(result_json, indent=2, ensure_ascii=False)
        
        # 完了メッセージ
        st.success("生成完了！以下のボタンからダウンロードしてください。")
        
        # ダウンロードボタン
        st.download_button(
            label="JSONをダウンロード (family_data.json)",
            data=json_str,
            file_name="family_data.json",
            mime="application/json"
        )
        
        # プレビュー
        with st.expander("生成されたJSONの中身を確認"):
            st.json(result_json)